#!/usr/bin/env bash
set -euo pipefail
root_dir=$(cd "$(dirname "$0")/.." && pwd)
cd "$root_dir"
project=social-post-security-test
test_port=${SOCIAL_POST_TEST_PORT:-18081}
base_url="http://127.0.0.1:$test_port"
callback_url="$base_url/api/oauth/linkedin/callback"
export APP_ENV=local DB_HOST=db DB_PORT=3306 DB_NAME=social_deck DB_USER=social_deck INITIAL_ADMIN_USERNAME=testadmin INITIAL_ADMIN_EMAIL=testadmin@example.test
export APP_ENCRYPTION_KEY=$(openssl rand -base64 32 | tr -d '\n') DB_PASSWORD=$(openssl rand -base64 24 | tr -d '\n') DB_ROOT_PASSWORD=$(openssl rand -base64 24 | tr -d '\n') INITIAL_ADMIN_PASSWORD=$(openssl rand -base64 24 | tr -d '\n')
compose=(docker compose -p "$project" -f docker-compose.yml -f docker-compose.test.yml)
cleanup(){ "${compose[@]}" down -v --remove-orphans >/dev/null 2>&1 || true; }
trap cleanup EXIT
"${compose[@]}" up -d --build --wait >/dev/null
"${compose[@]}" exec -T php php scripts/migrate.php >/dev/null
"${compose[@]}" exec -T php php scripts/migrate.php >/dev/null
"${compose[@]}" exec -T php php scripts/seed-admin.php >/dev/null
"${compose[@]}" exec -d php php -S 127.0.0.1:19090 tests/mock-linkedin-router.php
pass=0; fail=0
check(){ if "$@"; then printf 'PASS %s\n' "$*"; pass=$((pass+1)); else printf 'FAIL %s\n' "$*"; fail=$((fail+1)); fi; }
status(){ curl -sS -o /tmp/social-post-test-body -w '%{http_code}' "$@"; }
for path in /.env /.env.example /database/schema.sql /docker-compose.yml; do code=$(status "$base_url$path"); check sh -c '[ "$1" = 403 ] || [ "$1" = 404 ]' sh "$code"; done
code=$(status $base_url/api/ping); check test "$code" = 200
code=$(status -X POST $base_url/api/ping); check test "$code" = 405; check grep -qi '^Allow: GET' <(curl -sSI -X POST $base_url/api/ping)
code=$(status -X DELETE $base_url/api/legal); check test "$code" = 405
code=$(status $base_url/api/missing); check test "$code" = 404
code=$(status $base_url/api/oauth/linkedin/start); check test "$code" = 401
code=$(status -X POST -H 'Content-Type: application/json' --data '{' $base_url/api/auth/login); check test "$code" = 403
cookie=$(mktemp /tmp/social-post-test-cookie.XXXXXX); csrf_json=$(curl -sS -c "$cookie" $base_url/api/auth/csrf); csrf=$(printf '%s' "$csrf_json"|sed -n 's/.*"csrfToken":"\([a-f0-9]*\)".*/\1/p'); before=$(awk '$6=="SOCIALPOSTSESSID"{print $7}' "$cookie")
code=$(status -b "$cookie" -H 'Content-Type: application/json' -H "X-CSRF-Token: $csrf" --data '{' $base_url/api/auth/login); check test "$code" = 400
bad=$(printf '{"login":"%s","password":"wrong-password"}' "$INITIAL_ADMIN_USERNAME"); code=$(status -b "$cookie" -H 'Content-Type: application/json' -H "X-CSRF-Token: $csrf" --data "$bad" $base_url/api/auth/login); check test "$code" = 401
login=$(printf '{"login":"%s","password":"%s"}' "$INITIAL_ADMIN_USERNAME" "$INITIAL_ADMIN_PASSWORD"); response=$(curl -sS -b "$cookie" -c "$cookie" -H 'Content-Type: application/json' -H "X-CSRF-Token: $csrf" --data "$login" $base_url/api/auth/login); csrf=$(printf '%s' "$response"|sed -n 's/.*"csrfToken":"\([a-f0-9]*\)".*/\1/p'); after=$(awk '$6=="SOCIALPOSTSESSID"{print $7}' "$cookie"); check test -n "$csrf"; check test "$before" != "$after"
code=$(status $base_url/api/admin/providers); check test "$code" = 401
code=$(status -X PUT -H 'Content-Type: application/json' --data '{}' $base_url/api/admin/providers/linkedin); check test "$code" = 401
code=$(status $base_url/api/admin/email-settings);check test "$code" = 401
code=$(status -X PUT -H 'Content-Type: application/json' --data '{}' $base_url/api/admin/email-settings);check test "$code" = 401
email_settings='{"enabled":true,"host":"smtp.example.test","port":587,"encryption":"tls","user":"smtp-user","password":"smtp-secret-first","fromEmail":"sender@example.test","fromName":"Social Post","replyTo":"reply@example.test"}'
code=$(status -X PUT -b "$cookie" -H 'Content-Type: application/json' --data "$email_settings" $base_url/api/admin/email-settings);check test "$code" = 403
saved_email=$(curl -sS -X PUT -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data "$email_settings" $base_url/api/admin/email-settings);check sh -c 'printf %s "$1"|grep -q '"'"'"hasPassword":true'"'"' && ! printf %s "$1"|grep -q '"'"'smtp-secret-first\|"password"'"'"'' sh "$saved_email"
loaded_email=$(curl -sS -b "$cookie" $base_url/api/admin/email-settings);check sh -c 'printf %s "$1"|grep -q '"'"'"host":"smtp.example.test"'"'"' && printf %s "$1"|grep -q '"'"'"replyTo":"reply@example.test"'"'"' && ! printf %s "$1"|grep -q '"'"'smtp-secret-first\|"password"'"'"'' sh "$loaded_email"
email_cipher_before=$("${compose[@]}" exec -T db sh -lc 'mariadb -u"$MARIADB_USER" -p"$MARIADB_PASSWORD" "$MARIADB_DATABASE" -Nse "SELECT CONCAT(smtp_password_encrypted LIKE \"spsec:%\",\":\",smtp_password_encrypted LIKE \"%smtp-secret-first%\",\":\",SHA2(smtp_password_encrypted,256)) FROM email_settings WHERE id=1"');check sh -c '[ "${1%%:*}" = 1 ] && [ "$(printf %s "$1"|cut -d: -f2)" = 0 ]' sh "$email_cipher_before";email_hash_before=${email_cipher_before##*:}
email_keep='{"enabled":true,"host":"smtp.example.test","port":465,"encryption":"ssl","user":"smtp-user","password":"","fromEmail":"sender@example.test","fromName":"Social Post Reload","replyTo":"reply@example.test"}';code=$(status -X PUT -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data "$email_keep" $base_url/api/admin/email-settings);check test "$code" = 200;email_hash_after=$("${compose[@]}" exec -T db sh -lc 'mariadb -u"$MARIADB_USER" -p"$MARIADB_PASSWORD" "$MARIADB_DATABASE" -Nse "SELECT SHA2(smtp_password_encrypted,256) FROM email_settings WHERE id=1"');check test "$email_hash_before" = "$email_hash_after"
email_replace='{"enabled":true,"host":"smtp.example.test","port":25,"encryption":"none","user":"smtp-user","password":"smtp-secret-second","fromEmail":"sender@example.test","fromName":"Social Post","replyTo":""}';code=$(status -X PUT -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data "$email_replace" $base_url/api/admin/email-settings);check test "$code" = 200;email_hash_replaced=$("${compose[@]}" exec -T db sh -lc 'mariadb -u"$MARIADB_USER" -p"$MARIADB_PASSWORD" "$MARIADB_DATABASE" -Nse "SELECT SHA2(smtp_password_encrypted,256) FROM email_settings WHERE id=1"');check test "$email_hash_before" != "$email_hash_replaced"
for invalid_email_payload in '{"enabled":false,"host":"","port":587,"encryption":"tls","user":"","password":"","fromEmail":"kaputt","fromName":"","replyTo":""}' '{"enabled":false,"host":"","port":587,"encryption":"tls","user":"","password":"","fromEmail":"","fromName":"","replyTo":"kaputt"}';do code=$(status -X PUT -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data "$invalid_email_payload" $base_url/api/admin/email-settings);check test "$code" = 422;done
for invalid_email_payload in '{"enabled":false,"host":"","port":0,"encryption":"tls","user":"","password":"","fromEmail":"","fromName":"","replyTo":""}' '{"enabled":false,"host":"","port":587,"encryption":"starttls","user":"","password":"","fromEmail":"","fromName":"","replyTo":""}' '{"enabled":true,"host":"","port":587,"encryption":"tls","user":"","password":"","fromEmail":"sender@example.test","fromName":"","replyTo":""}' '{"enabled":true,"host":"smtp.example.test","port":587,"encryption":"tls","user":"","password":"","fromEmail":"","fromName":"","replyTo":""}';do code=$(status -X PUT -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data "$invalid_email_payload" $base_url/api/admin/email-settings);check test "$code" = 422;done
code=$(status $base_url/api/admin/text-blocks);check test "$code" = 401
code=$(status -X POST -H 'Content-Type: application/json' --data '{}' $base_url/api/admin/text-blocks);check test "$code" = 401
code=$(status -b "$cookie" $base_url/api/admin/text-blocks);check test "$code" = 200
text_block='{"title":"Standard CTA","key":"standard_cta","category":"Allgemein","content":"<img src=x onerror=alert(1)>","isActive":true,"sortOrder":20}'
code=$(status -X POST -b "$cookie" -H 'Content-Type: application/json' --data "$text_block" $base_url/api/admin/text-blocks);check test "$code" = 403
code=$(status -X POST -b "$cookie" -H 'X-CSRF-Token: 0000000000000000000000000000000000000000000000000000000000000000' -H 'Content-Type: application/json' --data "$text_block" $base_url/api/admin/text-blocks);check test "$code" = 403
created=$(curl -sS -X POST -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data "$text_block" $base_url/api/admin/text-blocks);text_block_id=$(printf '%s' "$created"|sed -n 's/.*"id":\([0-9]*\).*/\1/p');check test -n "$text_block_id"
blocks=$(curl -sS -b "$cookie" $base_url/api/admin/text-blocks);check sh -c 'printf %s "$1"|grep -q "standard_cta" && printf %s "$1"|grep -q "<img src=x onerror=alert(1)>"' sh "$blocks"
check sh -c 'printf %s "$1"|grep -q '"'"'"placeholderSyntax":"{{key}}"'"'"' && printf %s "$1"|grep -q '"'"'"isSystem":false'"'"' && ! printf %s "$1"|grep -q '"'"'"placeholderDefinitions"'"'"'' sh "$blocks"
code=$(status -X POST -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data '{"title":"Unbekannt","key":"unknown_placeholder","category":"Allgemein","content":"Hallo {{foo}}","isActive":true,"sortOrder":0}' $base_url/api/admin/text-blocks);check test "$code" = 422;check grep -q 'Unbekannter Platzhalter: {{foo}}' /tmp/social-post-test-body
code=$(status -X POST -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data '{"title":"Selbstreferenz","key":"self_reference","category":"Allgemein","content":"{{self_reference}}","isActive":true,"sortOrder":0}' $base_url/api/admin/text-blocks);check test "$code" = 422;check grep -q 'Zirkuläre Textbaustein-Referenz' /tmp/social-post-test-body
code=$(status -X POST -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data '{"title":"Syntax","key":"invalid_placeholder_syntax","category":"Allgemein","content":"Hallo {name}","isActive":true,"sortOrder":0}' $base_url/api/admin/text-blocks);check test "$code" = 422;check grep -q 'Ungültige Platzhaltersyntax' /tmp/social-post-test-body
code=$(status -X POST -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data '{"title":"Manipuliert","key":"forced_system","category":"","content":"Text","isActive":true,"isSystem":true,"sortOrder":0}' $base_url/api/admin/text-blocks);check test "$code" = 422
code=$(status -X POST -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data "$text_block" $base_url/api/admin/text-blocks);check test "$code" = 409
code=$(status -X POST -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data '{"title":"Ungültig","key":"bad key!","category":"","content":"Text","isActive":true,"sortOrder":0}' $base_url/api/admin/text-blocks);check test "$code" = 422
code=$(status -X POST -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data '{"title":"Ungültig","key":"bad_boolean","category":"","content":"Text","isActive":1,"sortOrder":0}' $base_url/api/admin/text-blocks);check test "$code" = 422
updated='{"title":"LinkedIn CTA","key":"linkedin_cta","category":"LinkedIn","content":"Nur Text","isActive":false,"sortOrder":5}';code=$(status -X PUT -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data "$updated" "$base_url/api/admin/text-blocks/$text_block_id");check test "$code" = 200
blocks=$(curl -sS -b "$cookie" $base_url/api/admin/text-blocks);check sh -c 'printf %s "$1"|grep -q "linkedin_cta" && printf %s "$1"|grep -q "\"isActive\":false" && printf %s "$1"|grep -q "\"sortOrder\":5"' sh "$blocks"
abschluss='{"title":"Abschluss","key":"abschluss","category":"Allgemein","content":"Viele Grüße","isActive":true,"sortOrder":1}';abschluss_created=$(curl -sS -X POST -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data "$abschluss" $base_url/api/admin/text-blocks);abschluss_id=$(printf '%s' "$abschluss_created"|sed -n 's/.*"id":\([0-9]*\).*/\1/p');check test -n "$abschluss_id"
public_blocks=$(curl -sS $base_url/api/text-blocks);check sh -c 'printf %s "$1"|grep -q "\"key\":\"abschluss\"" && ! printf %s "$1"|grep -q "\"key\":\"linkedin_cta\""' sh "$public_blocks"
resolved=$(curl -sS -H 'Content-Type: application/json' --data '{"text":"Hallo! {{abschluss}}"}' $base_url/api/text-blocks/resolve);check sh -c 'printf %s "$1"|grep -q "\"text\":\"Hallo! Viele Grüße\""' sh "$resolved"
code=$(status -H 'Content-Type: application/json' --data '{"text":"Hallo {{unbekannt}}"}' $base_url/api/text-blocks/resolve);check test "$code" = 422;check grep -q 'Unbekannter Platzhalter' /tmp/social-post-test-body
haupttext='{"title":"Haupttext","key":"haupttext","category":"Allgemein","content":"Hallo. {{abschluss}}","isActive":true,"sortOrder":2}';haupttext_created=$(curl -sS -X POST -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data "$haupttext" $base_url/api/admin/text-blocks);haupttext_id=$(printf '%s' "$haupttext_created"|sed -n 's/.*"id":\([0-9]*\).*/\1/p');check test -n "$haupttext_id"
code=$(status -X DELETE -b "$cookie" -H "X-CSRF-Token: $csrf" "$base_url/api/admin/text-blocks/$abschluss_id");check test "$code" = 409;check grep -q 'Haupttext' /tmp/social-post-test-body
abschluss_renamed='{"title":"Abschluss","key":"abschluss_neu","category":"Allgemein","content":"Viele Grüße","isActive":true,"sortOrder":1}';code=$(status -X PUT -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data "$abschluss_renamed" "$base_url/api/admin/text-blocks/$abschluss_id");check test "$code" = 409;check grep -q 'Haupttext' /tmp/social-post-test-body
cycle_a='{"title":"Zyklus A","key":"cycle_a","category":"Test","content":"Start","isActive":true,"sortOrder":0}';cycle_a_created=$(curl -sS -X POST -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data "$cycle_a" $base_url/api/admin/text-blocks);cycle_a_id=$(printf '%s' "$cycle_a_created"|sed -n 's/.*"id":\([0-9]*\).*/\1/p');cycle_b='{"title":"Zyklus B","key":"cycle_b","category":"Test","content":"{{cycle_a}}","isActive":true,"sortOrder":0}';cycle_b_created=$(curl -sS -X POST -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data "$cycle_b" $base_url/api/admin/text-blocks);cycle_b_id=$(printf '%s' "$cycle_b_created"|sed -n 's/.*"id":\([0-9]*\).*/\1/p');cycle_a_loop='{"title":"Zyklus A","key":"cycle_a","category":"Test","content":"{{cycle_b}}","isActive":true,"sortOrder":0}';code=$(status -X PUT -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data "$cycle_a_loop" "$base_url/api/admin/text-blocks/$cycle_a_id");check test "$code" = 422
"${compose[@]}" exec -T db sh -lc 'mariadb -u"$MARIADB_USER" -p"$MARIADB_PASSWORD" "$MARIADB_DATABASE" -e "INSERT INTO text_blocks(block_key,title,content,category,is_active,is_system,sort_order,created_at,updated_at) VALUES(\"required_system\",\"Benötigter Systemtext\",\"Standardinhalt\",\"System\",1,1,0,NOW(),NOW())"';system_id=$("${compose[@]}" exec -T db sh -lc 'mariadb -u"$MARIADB_USER" -p"$MARIADB_PASSWORD" "$MARIADB_DATABASE" -Nse "SELECT id FROM text_blocks WHERE block_key=\"required_system\""')
blocks=$(curl -sS -b "$cookie" $base_url/api/admin/text-blocks);check sh -c 'printf %s "$1"|grep -q '"'"'"key":"required_system"'"'"' && printf %s "$1"|grep -q '"'"'"isSystem":true'"'"'' sh "$blocks"
system_status_manipulation='{"title":"Manipulierter Systemtext","key":"required_system","category":"System","content":"Text","isActive":true,"isSystem":false,"sortOrder":0}';code=$(status -X PUT -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data "$system_status_manipulation" "$base_url/api/admin/text-blocks/$system_id");check test "$code" = 422
system_update='{"title":"Bearbeiteter Systemtext","key":"required_system","category":"System","content":"Geänderter Inhalt {{abschluss}}","isActive":true,"sortOrder":9}';code=$(status -X PUT -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data "$system_update" "$base_url/api/admin/text-blocks/$system_id");check test "$code" = 200
system_key_change='{"title":"Systemtext","key":"changed_system","category":"System","content":"Text","isActive":true,"sortOrder":0}';code=$(status -X PUT -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data "$system_key_change" "$base_url/api/admin/text-blocks/$system_id");check test "$code" = 409
system_disable='{"title":"Systemtext","key":"required_system","category":"System","content":"Text","isActive":false,"sortOrder":0}';code=$(status -X PUT -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data "$system_disable" "$base_url/api/admin/text-blocks/$system_id");check test "$code" = 409
code=$(status -X DELETE -b "$cookie" -H "X-CSRF-Token: $csrf" "$base_url/api/admin/text-blocks/$system_id");check test "$code" = 409
haupttext_plain='{"title":"Haupttext","key":"haupttext","category":"Allgemein","content":"Ohne Referenz","isActive":true,"sortOrder":2}';code=$(status -X PUT -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data "$haupttext_plain" "$base_url/api/admin/text-blocks/$haupttext_id");check test "$code" = 200
code=$(status -X DELETE -b "$cookie" -H "X-CSRF-Token: $csrf" "$base_url/api/admin/text-blocks/$haupttext_id");check test "$code" = 200;code=$(status -X DELETE -b "$cookie" -H "X-CSRF-Token: $csrf" "$base_url/api/admin/text-blocks/$cycle_b_id");check test "$code" = 200;code=$(status -X DELETE -b "$cookie" -H "X-CSRF-Token: $csrf" "$base_url/api/admin/text-blocks/$cycle_a_id");check test "$code" = 200
"${compose[@]}" exec -T db sh -lc 'mariadb -u"$MARIADB_USER" -p"$MARIADB_PASSWORD" "$MARIADB_DATABASE" -e "DELETE FROM text_blocks WHERE block_key=\"required_system\""'
code=$(status -X DELETE -b "$cookie" -H "X-CSRF-Token: $csrf" "$base_url/api/admin/text-blocks/$abschluss_id");check test "$code" = 200
code=$(status -X DELETE -b "$cookie" -H "X-CSRF-Token: $csrf" "$base_url/api/admin/text-blocks/$text_block_id");check test "$code" = 200
blocks=$(curl -sS -b "$cookie" $base_url/api/admin/text-blocks);check sh -c '! printf %s "$1"|grep -q "linkedin_cta"' sh "$blocks"
code=$(status -b "$cookie" -H 'Accept: application/json' -H "X-CSRF-Token: $csrf" $base_url/api/oauth/linkedin/start);check test "$code" = 422
"${compose[@]}" exec -T -e TEST_CALLBACK_URL="$callback_url" db sh -lc 'mariadb -u"$MARIADB_USER" -p"$MARIADB_PASSWORD" "$MARIADB_DATABASE" -e "INSERT INTO provider_configs(provider_id,enabled,client_id,client_secret_encrypted,redirect_uri,scopes,created_at,updated_at) VALUES(\"linkedin\",1,NULL,NULL,\"$TEST_CALLBACK_URL\",\"openid\\nprofile\",NOW(),NOW())"';code=$(status -b "$cookie" -H 'Accept: application/json' -H "X-CSRF-Token: $csrf" $base_url/api/oauth/linkedin/start);check test "$code" = 422
"${compose[@]}" exec -T db sh -lc 'mariadb -u"$MARIADB_USER" -p"$MARIADB_PASSWORD" "$MARIADB_DATABASE" -e "UPDATE provider_configs SET client_id=\"mock-client\" WHERE provider_id=\"linkedin\""';code=$(status -b "$cookie" -H 'Accept: application/json' -H "X-CSRF-Token: $csrf" $base_url/api/oauth/linkedin/start);check test "$code" = 422
linkedin_config=$(printf '{"enabled":true,"clientId":"mock-client","clientSecret":"mock-client-secret","redirectUri":"%s","scopes":"openid profile"}' "$callback_url");code=$(status -X PUT -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data "$linkedin_config" $base_url/api/admin/providers/linkedin);check test "$code" = 200
oauth_start=$(curl -sS -b "$cookie" -H 'Accept: application/json' -H "X-CSRF-Token: $csrf" $base_url/api/oauth/linkedin/start);oauth_url=$(printf '%s' "$oauth_start"|sed -n 's/.*"authorizationUrl":"\([^"]*\)".*/\1/p'|sed 's/\\u0026/\&/g');state=$(printf '%s' "$oauth_url"|sed -n 's/.*[?&]state=\([^&]*\).*/\1/p');check test -n "$state";check sh -c 'printf %s "$1"|grep -q "response_type=code"' sh "$oauth_url"
code=$(status -b "$cookie" "$base_url/api/oauth/linkedin/callback?state=wrong&code=good-code");check test "$code" = 403
oauth_start=$(curl -sS -b "$cookie" -H 'Accept: application/json' -H "X-CSRF-Token: $csrf" $base_url/api/oauth/linkedin/start);state=$(printf '%s' "$oauth_start"|sed -n 's/.*state%3D\([^%"]*\).*/\1/p');[[ -n $state ]]||state=$(printf '%s' "$oauth_start"|sed -n 's/.*state=\([^&"\\]*\).*/\1/p');code=$(status -b "$cookie" "$base_url/api/oauth/linkedin/callback?state=$state");check test "$code" = 422;code=$(status -b "$cookie" "$base_url/api/oauth/linkedin/callback?state=$state&code=good-code");check test "$code" = 403
oauth_start=$(curl -sS -b "$cookie" -H 'Accept: application/json' -H "X-CSRF-Token: $csrf" $base_url/api/oauth/linkedin/start);state=$(printf '%s' "$oauth_start"|sed -n 's/.*state=\([^&"\\]*\).*/\1/p');code=$(status -b "$cookie" "$base_url/api/oauth/linkedin/callback?state=$state&error=user_cancelled_authorize");check test "$code" = 303
for failure_code in token-failure identity-failure; do oauth_start=$(curl -sS -b "$cookie" -H 'Accept: application/json' -H "X-CSRF-Token: $csrf" $base_url/api/oauth/linkedin/start);state=$(printf '%s' "$oauth_start"|sed -n 's/.*state=\([^&"\\]*\).*/\1/p');code=$(status -b "$cookie" "$base_url/api/oauth/linkedin/callback?state=$state&code=$failure_code");check test "$code" = 502;done
oauth_start=$(curl -sS -b "$cookie" -H 'Accept: application/json' -H "X-CSRF-Token: $csrf" $base_url/api/oauth/linkedin/start);state=$(printf '%s' "$oauth_start"|sed -n 's/.*state=\([^&"\\]*\).*/\1/p');callback_headers=$(mktemp /tmp/social-post-callback.XXXXXX);code=$(curl -sS -D "$callback_headers" -o /tmp/social-post-test-body -w '%{http_code}' -b "$cookie" "$base_url/api/oauth/linkedin/callback?state=$state&code=good-code");check test "$code" = 303;check sh -c '! grep -qi "mock-access-token\|mock-refresh-token" "$1" /tmp/social-post-test-body' sh "$callback_headers"
account_row=$("${compose[@]}" exec -T db sh -lc 'mariadb -u"$MARIADB_USER" -p"$MARIADB_PASSWORD" "$MARIADB_DATABASE" -Nse "SELECT CONCAT(id,\":\",status,\":\",access_token_encrypted LIKE \"spsec:%\",\":\",refresh_token_encrypted LIKE \"spsec:%\") FROM social_accounts WHERE provider_id=\"linkedin\" AND external_account_id=\"linkedin-test-account\""');check sh -c '[ "${1#*:}" = "connected:1:1" ]' sh "$account_row";account_id=${account_row%%:*};providers=$(curl -sS -b "$cookie" $base_url/api/admin/providers);check sh -c 'printf %s "$1"|grep -q "LinkedIn Test Account" && ! printf %s "$1"|grep -q "mock-access-token"' sh "$providers"
code=$(status -X POST -H 'Content-Type: application/json' --data "{\"accountId\":$account_id}" $base_url/api/oauth/linkedin/disconnect);check test "$code" = 401
code=$(status -X POST -b "$cookie" -H 'Content-Type: application/json' --data "{\"accountId\":$account_id}" $base_url/api/oauth/linkedin/disconnect);check test "$code" = 403
code=$(status -X POST -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data "{\"accountId\":$account_id}" $base_url/api/oauth/linkedin/disconnect);check test "$code" = 200;disconnected=$("${compose[@]}" exec -T db sh -lc 'mariadb -u"$MARIADB_USER" -p"$MARIADB_PASSWORD" "$MARIADB_DATABASE" -Nse "SELECT CONCAT(status,\":\",access_token_encrypted IS NULL,\":\",refresh_token_encrypted IS NULL) FROM social_accounts WHERE provider_id=\"linkedin\" AND external_account_id=\"linkedin-test-account\""');check test "$disconnected" = disconnected:1:1
for token in missing empty wrong; do header=(); [[ $token == empty ]]&&header=(-H 'X-CSRF-Token:'); [[ $token == wrong ]]&&header=(-H 'X-CSRF-Token: 0000000000000000000000000000000000000000000000000000000000000000'); code=$(status -X PUT -b "$cookie" "${header[@]}" -H 'Content-Type: application/json' --data '{"imprint":"","privacy":""}' $base_url/api/admin/legal); check test "$code" = 403; done
code=$(status -X PUT -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data '{"enabled":"false","clientId":"","clientSecret":"","redirectUri":"","scopes":""}' $base_url/api/admin/providers/instagram); check test "$code" = 422
code=$(status -X PUT -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data '{"enabled":true,"clientId":"","clientSecret":"","redirectUri":"bad","scopes":""}' $base_url/api/admin/providers/instagram); check test "$code" = 422
code=$(status -X PUT -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data '{"enabled":true,"clientId":"id","clientSecret":"secret-value","redirectUri":"http://localhost/callback","scopes":["scope_a","scope_b"]}' $base_url/api/admin/providers/instagram); check test "$code" = 200
providers=$(curl -sS -b "$cookie" $base_url/api/admin/providers); check sh -c '! printf %s "$1" | grep -q secret-value' sh "$providers"; check sh -c 'printf %s "$1" | grep -q hasClientSecret' sh "$providers"
cipher_before=$("${compose[@]}" exec -T db sh -lc 'mariadb -u"$MARIADB_USER" -p"$MARIADB_PASSWORD" "$MARIADB_DATABASE" -Nse "SELECT SHA2(client_secret_encrypted,256) FROM provider_configs WHERE provider_id=\"instagram\""');code=$(status -X PUT -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data '{"enabled":true,"clientId":"id","clientSecret":"","redirectUri":"http://localhost/callback","scopes":"scope_a"}' $base_url/api/admin/providers/instagram);cipher_after=$("${compose[@]}" exec -T db sh -lc 'mariadb -u"$MARIADB_USER" -p"$MARIADB_PASSWORD" "$MARIADB_DATABASE" -Nse "SELECT SHA2(client_secret_encrypted,256) FROM provider_configs WHERE provider_id=\"instagram\""');check test "$cipher_before" = "$cipher_after"
xss='<img src=x onerror=alert(1)>'; legal=$(printf '{"imprint":"%s","privacy":"Text"}' "$xss"); code=$(status -X PUT -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data "$legal" $base_url/api/admin/legal);check test "$code" = 200; dom=$(chromium --headless --no-sandbox --disable-gpu --virtual-time-budget=2000 --dump-dom $base_url/\#/impressum 2>/dev/null);check sh -c '! printf %s "$1"|grep -q "<img src=\"x\""' sh "$dom"
oversized=$(head -c 100001 /dev/zero|tr '\0' x);legal=$(printf '{"imprint":"%s","privacy":"Text"}' "$oversized");code=$(status -X PUT -b "$cookie" -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data "$legal" $base_url/api/admin/legal);check test "$code" = 422
new_password=$(openssl rand -base64 24|tr -d '\n');password_payload=$(printf '{"currentPassword":"%s","newPassword":"%s","newPasswordRepeat":"%s"}' "$INITIAL_ADMIN_PASSWORD" "$new_password" "$new_password");sid_before=$(awk '$6=="SOCIALPOSTSESSID"{print $7}' "$cookie");password_response=$(curl -sS -b "$cookie" -c "$cookie" -X PUT -H "X-CSRF-Token: $csrf" -H 'Content-Type: application/json' --data "$password_payload" $base_url/api/admin/password);csrf=$(printf '%s' "$password_response"|sed -n 's/.*"csrfToken":"\([a-f0-9]*\)".*/\1/p');sid_after=$(awk '$6=="SOCIALPOSTSESSID"{print $7}' "$cookie");check test "$sid_before" != "$sid_after";check test -n "$csrf"
code=$(status -X POST -b "$cookie" -c "$cookie" -H "X-CSRF-Token: $csrf" $base_url/api/auth/logout);check test "$code" = 200;code=$(status -b "$cookie" $base_url/api/auth/me);check test "$code" = 401
csrf_json=$(curl -sS -c "$cookie" $base_url/api/auth/csrf);csrf=$(printf '%s' "$csrf_json"|sed -n 's/.*"csrfToken":"\([a-f0-9]*\)".*/\1/p');login=$(printf '{"login":"%s","password":"%s"}' "$INITIAL_ADMIN_USERNAME" "$new_password");response=$(curl -sS -b "$cookie" -c "$cookie" -H 'Content-Type: application/json' -H "X-CSRF-Token: $csrf" --data "$login" $base_url/api/auth/login);csrf=$(printf '%s' "$response"|sed -n 's/.*"csrfToken":"\([a-f0-9]*\)".*/\1/p');check test -n "$csrf"
"${compose[@]}" exec -T db sh -lc 'mariadb -u"$MARIADB_USER" -p"$MARIADB_PASSWORD" "$MARIADB_DATABASE" -e "UPDATE users SET role=\"user\" WHERE username=\"testadmin\""';code=$(status -b "$cookie" $base_url/api/admin/providers);check test "$code" = 403;"${compose[@]}" exec -T db sh -lc 'mariadb -u"$MARIADB_USER" -p"$MARIADB_PASSWORD" "$MARIADB_DATABASE" -e "UPDATE users SET role=\"admin\" WHERE username=\"testadmin\""'
csrf_json=$(curl -sS -c "$cookie" $base_url/api/auth/csrf);csrf=$(printf '%s' "$csrf_json"|sed -n 's/.*"csrfToken":"\([a-f0-9]*\)".*/\1/p');response=$(curl -sS -b "$cookie" -c "$cookie" -H 'Content-Type: application/json' -H "X-CSRF-Token: $csrf" --data "$login" $base_url/api/auth/login);csrf=$(printf '%s' "$response"|sed -n 's/.*"csrfToken":"\([a-f0-9]*\)".*/\1/p');"${compose[@]}" exec -T db sh -lc 'mariadb -u"$MARIADB_USER" -p"$MARIADB_PASSWORD" "$MARIADB_DATABASE" -e "UPDATE users SET is_active=0 WHERE username=\"testadmin\""';code=$(status -b "$cookie" $base_url/api/admin/providers);check test "$code" = 401;"${compose[@]}" exec -T db sh -lc 'mariadb -u"$MARIADB_USER" -p"$MARIADB_PASSWORD" "$MARIADB_DATABASE" -e "UPDATE users SET is_active=1 WHERE username=\"testadmin\""'
crypto=$("${compose[@]}" exec -T php php tests/crypto-unit.php);while IFS= read -r line;do printf '%s\n' "$line";pass=$((pass+1));done<<<"$crypto"
oauth_state=$("${compose[@]}" exec -T php php tests/oauth-state-unit.php);while IFS= read -r line;do printf '%s\n' "$line";pass=$((pass+1));done<<<"$oauth_state"
text_block_resolution=$("${compose[@]}" exec -T php php tests/text-block-resolution-unit.php);while IFS= read -r line;do printf '%s\n' "$line";pass=$((pass+1));done<<<"$text_block_resolution"
text_block_seed=$("${compose[@]}" exec -T php php tests/text-block-system-seed.php);while IFS= read -r line;do printf '%s\n' "$line";pass=$((pass+1));done<<<"$text_block_seed"
for value in '' invalid YWJj;do if "${compose[@]}" exec -T -e APP_ENCRYPTION_KEY="$value" php php tests/crypto-unit.php key >/dev/null;then printf 'PASS Encryption-Key-Fehlerfall\n';pass=$((pass+1));else printf 'FAIL Encryption-Key-Fehlerfall\n';fail=$((fail+1));fi;done
browser=$(chromium --headless --no-sandbox --disable-gpu --virtual-time-budget=4000 --dump-dom $base_url/tests/test.html 2>/dev/null);browser_pass=$(printf '%s' "$browser"|awk '{n+=gsub(/PASS /,"&")}END{print n+0}');browser_fail=$(printf '%s' "$browser"|awk '{n+=gsub(/FAIL /,"&")}END{print n+0}');pass=$((pass+browser_pass));fail=$((fail+browser_fail));printf 'Browser: PASS=%d FAIL=%d\n' "$browser_pass" "$browser_fail"
printf 'TOTAL PASS=%d FAIL=%d\n' "$pass" "$fail";test "$fail" -eq 0
