CREATE TABLE IF NOT EXISTS campaigns (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(190) NOT NULL,
 base_reply_text TEXT NOT NULL,
 status ENUM('draft','ready','partially_published','published','cancelled') NOT NULL DEFAULT 'draft',
 created_by BIGINT UNSIGNED NOT NULL,
 platform_settings_json JSON NOT NULL,
 revision INT UNSIGNED NOT NULL DEFAULT 1,
 review_json JSON NULL,
 review_token_hash CHAR(64) NULL,
 review_expires_at DATETIME NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS engagement_items (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 created_by BIGINT UNSIGNED NOT NULL,
 provider_id VARCHAR(50) NOT NULL,
 social_account_id BIGINT UNSIGNED NULL,
 external_author_id VARCHAR(255) NULL,
 author_display_name VARCHAR(255) NOT NULL,
 external_post_id VARCHAR(500) NOT NULL,
 external_post_urn VARCHAR(500) NULL,
 external_post_url VARCHAR(2048) NULL,
 dedupe_key CHAR(64) NOT NULL,
 post_excerpt TEXT NOT NULL,
 published_at DATETIME NULL,
 discovered_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 relevance_score SMALLINT UNSIGNED NULL CHECK(relevance_score <= 100),
 relevance_reason VARCHAR(500) NULL,
 relevance_source VARCHAR(50) NULL,
 status ENUM('new','selected','edited','commented','ignored') NOT NULL DEFAULT 'new',
 metadata_json JSON NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (created_by) REFERENCES users(id),
 FOREIGN KEY (social_account_id) REFERENCES social_accounts(id) ON DELETE SET NULL,
 UNIQUE KEY uq_engagement_source (created_by,provider_id,dedupe_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS campaign_targets (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 campaign_id BIGINT UNSIGNED NOT NULL,
 engagement_item_id BIGINT UNSIGNED NOT NULL,
 provider_id VARCHAR(50) NOT NULL,
 social_account_id BIGINT UNSIGNED NULL,
 external_post_id VARCHAR(500) NOT NULL,
 external_post_urn VARCHAR(500) NULL,
 author_display_name VARCHAR(255) NULL,
 enabled TINYINT(1) NOT NULL DEFAULT 1,
 reply_text TEXT NOT NULL,
 reply_is_customized TINYINT(1) NOT NULL DEFAULT 0,
 status ENUM('draft','ready','publishing','published','failed','disabled') NOT NULL DEFAULT 'draft',
 external_comment_id VARCHAR(500) NULL,
 published_at DATETIME NULL,
 error_code VARCHAR(100) NULL,
 error_message VARCHAR(500) NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
 FOREIGN KEY (engagement_item_id) REFERENCES engagement_items(id),
 FOREIGN KEY (social_account_id) REFERENCES social_accounts(id) ON DELETE SET NULL,
 UNIQUE KEY uq_campaign_item (campaign_id,engagement_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
