<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
try {
    encryptionKey(); $method=$_SERVER['REQUEST_METHOD']??'GET'; $path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH);
    providerAppRoutes((string)$path,$method);
    campaignRoutes((string)$path,$method);
    $routes=['/api/ping'=>['GET'],'/api/auth/csrf'=>['GET'],'/api/auth/login'=>['POST'],'/api/auth/logout'=>['POST'],'/api/auth/me'=>['GET'],'/api/posts'=>['GET'],'/api/text-blocks'=>['GET'],'/api/text-blocks/resolve'=>['POST'],'/api/admin/providers'=>['GET'],'/api/admin/providers/linkedin/channels/sync'=>['POST'],'/api/admin/linkedin/test-post'=>['POST'],'/api/admin/legal'=>['GET','PUT'],'/api/admin/text-blocks'=>['GET','POST'],'/api/admin/email-settings'=>['GET','PUT'],'/api/legal'=>['GET'],'/api/admin/password'=>['PUT'],'/api/oauth/linkedin/start'=>['GET'],'/api/oauth/linkedin/callback'=>['GET'],'/api/oauth/linkedin/disconnect'=>['POST']];
    $providerRoute=preg_match('#^/api/admin/providers/([a-z0-9-]+)$#',(string)$path,$matches)===1;
    $textBlockRoute=preg_match('#^/api/admin/text-blocks/([1-9][0-9]*)$#',(string)$path,$textBlockMatches)===1;
    if(isset($routes[$path])&&!in_array($method,$routes[$path],true))fail('METHOD_NOT_ALLOWED','HTTP-Methode nicht erlaubt.',405,['Allow'=>implode(', ',$routes[$path])]);
    if($providerRoute&&$method!=='PUT')fail('METHOD_NOT_ALLOWED','HTTP-Methode nicht erlaubt.',405,['Allow'=>'PUT']);
    if($textBlockRoute&&!in_array($method,['PUT','DELETE'],true))fail('METHOD_NOT_ALLOWED','HTTP-Methode nicht erlaubt.',405,['Allow'=>'PUT, DELETE']);
    if($path==='/api/ping'){db()->query('SELECT 1');ok(['database'=>'connected']);}
    if($path==='/api/auth/csrf')ok(['csrfToken'=>csrfToken()]);
    if($path==='/api/auth/login'){
        requireCsrf();if(currentUserId()!==null)fail('ALREADY_AUTHENTICATED','Bereits angemeldet.',409);$data=input();$login=requireStringField($data,'login',190);$password=requireStringField($data,'password',1024,false);if($login===''||$password==='')fail('INVALID_INPUT','Login und Passwort sind erforderlich.',422);
        $wait=(float)($_SESSION['login_wait_until']??0);if($wait>microtime(true))usleep((int)min(1000000,($wait-microtime(true))*1000000));$stmt=db()->prepare('SELECT id,username,email,password_hash,role,is_active FROM users WHERE username=? OR email=? LIMIT 2');$stmt->execute([$login,$login]);$users=$stmt->fetchAll();$user=count($users)===1?$users[0]:null;
        if(!$user||(int)$user['is_active']!==1||!password_verify($password,$user['password_hash'])){usleep(250000);$attempts=min(5,(int)($_SESSION['login_failures']??0)+1);$_SESSION['login_failures']=$attempts;$_SESSION['login_wait_until']=microtime(true)+(0.2*$attempts);fail('INVALID_CREDENTIALS','Ungültige Anmeldung.',401);}
        session_regenerate_id(true);$_SESSION=['user_id'=>(int)$user['id'],'csrf'=>bin2hex(random_bytes(32))];$now=date('Y-m-d H:i:s');db()->prepare('UPDATE users SET last_login_at=?,updated_at=? WHERE id=?')->execute([$now,$now,$user['id']]);ok(['user'=>publicUser($user),'csrfToken'=>csrfToken()]);
    }
    if($path==='/api/auth/logout'){requireAuth();requireCsrf();destroyAppSession();ok(['loggedOut'=>true]);}
    if($path==='/api/auth/me'){$user=requireAuth();ok(['user'=>publicUser($user),'csrfToken'=>csrfToken()]);}
    if($path==='/api/posts')listPosts();
    if($path==='/api/text-blocks')listActiveTextBlocks();
    if($path==='/api/text-blocks/resolve')resolvePostText();
    if($path==='/api/oauth/linkedin/start')startLinkedInOAuth();
    if($path==='/api/oauth/linkedin/callback')linkedInCallback();
    if($path==='/api/oauth/linkedin/disconnect')disconnectLinkedIn();
    if($path==='/api/admin/providers/linkedin/channels/sync')syncLinkedInOrganizationChannels();if($path==='/api/admin/linkedin/test-post')publishLinkedInTestPost();
    if($path==='/api/admin/text-blocks'&&$method==='GET')listTextBlocks();
    if($path==='/api/admin/text-blocks'&&$method==='POST')createTextBlock();
    if($textBlockRoute&&$method==='PUT')updateTextBlock((int)$textBlockMatches[1]);
    if($textBlockRoute&&$method==='DELETE')deleteTextBlock((int)$textBlockMatches[1]);
    if($path==='/api/admin/email-settings'&&$method==='GET')getEmailSettings();
    if($path==='/api/admin/email-settings'&&$method==='PUT')saveEmailSettings();
    if($path==='/api/admin/providers'){
        requireAdmin();$rows=db()->query('SELECT *,configured_scopes scopes FROM provider_apps ORDER BY id')->fetchAll();$byId=[];$apps=[];foreach($rows as $row){$byId[$row['provider_id']]??=$row;$apps[$row['provider_id']][]=publicProviderApp($row);}$accountRows=db()->query("SELECT a.id,a.provider_id,a.provider_app_id,a.external_account_id,a.display_name,a.account_type,a.token_expires_at,a.scopes,a.status,p.enabled app_enabled FROM social_accounts a JOIN provider_apps p ON p.id=a.provider_app_id ORDER BY a.id")->fetchAll();$accounts=[];foreach($accountRows as $account)$accounts[$account['provider_id']][]=['id'=>(int)$account['id'],'providerAppId'=>(int)$account['provider_app_id'],'appEnabled'=>(bool)$account['app_enabled'],'externalAccountId'=>$account['external_account_id'],'displayName'=>$account['display_name'],'accountType'=>$account['account_type'],'tokenExpiresAt'=>$account['token_expires_at'],'scopes'=>$account['scopes'],'status'=>$account['status'],'campaignCapabilities'=>$account['app_enabled']?(campaignProvider($account['provider_id'])?->capabilities($account)??['read'=>false,'write'=>false,'postRead'=>false]):['read'=>false,'write'=>false,'postRead'=>false]];$channelRows=db()->query("SELECT c.*,a.status account_status,a.token_expires_at,p.id provider_app_id,p.name app_name,p.enabled app_enabled FROM social_channels c JOIN social_accounts a ON a.id=c.social_account_id JOIN provider_apps p ON p.id=a.provider_app_id ORDER BY c.channel_type,p.id,c.id")->fetchAll();$channels=[];foreach($channelRows as $channel)$channels[$channel['provider_id']][]=['id'=>(int)$channel['id'],'providerAppId'=>(int)$channel['provider_app_id'],'appName'=>$channel['app_name'],'socialAccountId'=>(int)$channel['social_account_id'],'providerId'=>$channel['provider_id'],'externalChannelId'=>$channel['external_channel_id'],'channelType'=>$channel['channel_type'],'displayName'=>$channel['display_name'],'externalUrn'=>$channel['external_urn'],'role'=>$channel['role'],'canPublish'=>(bool)$channel['can_publish']&&(bool)$channel['app_enabled']&&$channel['account_status']==='connected'&&(!$channel['token_expires_at']||strtotime($channel['token_expires_at'])>time()),'status'=>$channel['app_enabled']?$channel['status']:'inactive','lastSyncedAt'=>$channel['last_synced_at']];$result=[];
        foreach(providerDefinitions() as $id=>$definition){$row=$byId[$id]??[];$providerAccounts=$accounts[$id]??[];$providerChannels=$channels[$id]??[];$extra=[];if($id==='linkedin'){$connected=array_values(array_filter($providerAccounts,fn(array $account)=>$account['status']==='connected'));$discovery=providerCapabilityAccount('linkedin','organizationDiscovery');$tokenScopes=linkedInScopeList($discovery['scopes']??null);$extra=['oauthResult'=>linkedInLastOAuthResult(),'channelAccess'=>!$connected?['status'=>'not_connected','message'=>'Persönliches Profil ist noch nicht verbunden.']:(!hasLinkedInOrganizationDiscoveryScope($tokenScopes)?['status'=>'permission_required','message'=>'Persönliches Profil verfügbar. Unternehmensseiten benötigen die Community Management API und den Scope r_organization_admin.','missingScopes'=>['r_organization_admin'],'reauthorizationRequired'=>true]:['status'=>'available','message'=>'Unternehmensseiten können manuell aktualisiert werden.','missingScopes'=>[],'reauthorizationRequired'=>false])];}$result[]=array_merge($definition,['apps'=>$apps[$id]??[],'capabilityMatrix'=>providerCapabilityMatrix($id),'enabled'=>count(array_filter($apps[$id]??[],fn($a)=>$a['enabled']))>0,'clientId'=>$row['client_id']??'','hasClientSecret'=>!empty($row['client_secret_encrypted']),'redirectUri'=>$row['redirect_uri']??'','scopes'=>$row['scopes']??implode("\n",$definition['defaultScopes']),'accounts'=>$providerAccounts,'channels'=>$providerChannels],$extra);}ok(['providers'=>$result]);
    }
    if($providerRoute){
        requireAdmin();requireCsrf();$providerId=$matches[1];if(!providerDefinition($providerId))fail('NOT_FOUND','Provider nicht gefunden.',404);
        $old=soleProviderApp($providerId);$data=input();$data['name']=$old['name']??(providerDefinition($providerId)['name'].' Standard');$data['purpose']=$old['purpose']??null;
        $app=saveProviderApp($providerId,$old?(int)$old['id']:null,$data);ok(['providerId'=>$providerId,'hasClientSecret'=>$app['hasClientSecret']]);
    }
    if($path==='/api/admin/legal'&&$method==='GET'){requireAdmin();$row=db()->query('SELECT imprint,privacy FROM legal_settings WHERE id=1')->fetch();ok(['imprint'=>$row['imprint']??'','privacy'=>$row['privacy']??'']);}
    if($path==='/api/legal'){$row=db()->query('SELECT imprint,privacy FROM legal_settings WHERE id=1')->fetch();ok(['imprint'=>$row['imprint']??'','privacy'=>$row['privacy']??'']);}
    if($path==='/api/admin/legal'&&$method==='PUT'){requireAdmin();requireCsrf();$data=input();$imprint=requireStringField($data,'imprint',100000,false);$privacy=requireStringField($data,'privacy',100000,false);$now=date('Y-m-d H:i:s');db()->prepare('INSERT INTO legal_settings(id,imprint,privacy,updated_at) VALUES(1,?,?,?) ON DUPLICATE KEY UPDATE imprint=VALUES(imprint),privacy=VALUES(privacy),updated_at=VALUES(updated_at)')->execute([$imprint,$privacy,$now]);ok();}
    if($path==='/api/admin/password'){ $user=requireAdmin();requireCsrf();$data=input();$current=requireStringField($data,'currentPassword',1024,false);$new=requireStringField($data,'newPassword',1024,false);$repeat=requireStringField($data,'newPasswordRepeat',1024,false);if($current==='')fail('INVALID_INPUT','Aktuelles Passwort ist erforderlich.',422);if(strlen($new)<12||$new!==$repeat)fail('INVALID_INPUT','Neues Passwort muss mindestens 12 Zeichen haben und übereinstimmen.',422);$stmt=db()->prepare('SELECT password_hash FROM users WHERE id=?');$stmt->execute([$user['id']]);$hash=(string)$stmt->fetchColumn();if(!password_verify($current,$hash))fail('INVALID_CREDENTIALS','Aktuelles Passwort ist falsch.',422);if(password_verify($new,$hash))fail('INVALID_INPUT','Das neue Passwort muss sich unterscheiden.',422);db()->prepare('UPDATE users SET password_hash=?,updated_at=? WHERE id=?')->execute([password_hash($new,PASSWORD_DEFAULT),date('Y-m-d H:i:s'),$user['id']]);session_regenerate_id(true);$_SESSION['csrf']=bin2hex(random_bytes(32));ok(['csrfToken'=>csrfToken()]);}
    fail('NOT_FOUND','Endpunkt nicht gefunden.',404);
}catch(OAuthException $exception){error_log('SocialPost LinkedIn OAuth failure: '.$exception->errorCode);if(($path??'')==='/api/oauth/linkedin/callback'&&!str_contains($_SERVER['HTTP_ACCEPT']??'','application/json'))linkedInAdminRedirect('failed',$exception->errorCode);fail($exception->errorCode,$exception->getMessage(),$exception->httpStatus);}catch(Throwable $exception){$requestId=bin2hex(random_bytes(8));error_log("SocialPost request $requestId failed: ".get_class($exception));if(($path??'')==='/api/ping'&&$exception instanceof PDOException)fail('DATABASE_UNAVAILABLE','Datenbank momentan nicht verfügbar.',503);fail('INTERNAL_ERROR','Interner Serverfehler. Referenz: '.$requestId,500);}
