<?php
declare(strict_types=1);
function linkedInPostValidationLog(string $code,array $context):void{error_log('SocialPost LinkedIn post '.json_encode(['phase'=>'linkedin_post_validation','validationCode'=>$code,'hasText'=>(bool)($context['hasText']??false),'hasLink'=>(bool)($context['hasLink']??false),'linkValid'=>(bool)($context['linkValid']??false),'channelPresent'=>(bool)($context['channelPresent']??false),'channelPublishable'=>(bool)($context['channelPublishable']??false),'scopePresent'=>(bool)($context['scopePresent']??false),'confirmed'=>(bool)($context['confirmed']??false)],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE));}
function linkedInPostValidationFailure(string $code,string $message,array $context,int $status=422):never{linkedInPostValidationLog($code,$context);throw new OAuthException($code,$message,$status);}
function linkedInPostLink(array $data,array &$context):?string{$value=$data['linkUrl']??'';$context['hasLink']=is_string($value)&&trim($value)!=='';if(!is_string($value))linkedInPostValidationFailure('LINKEDIN_POST_INVALID_URL','LinkedIn-Beitrag konnte nicht veröffentlicht werden: Der Link ist keine gültige absolute HTTP(S)-URL.',$context);$link=trim($value);if($link===''){$context['linkValid']=true;return null;}$scheme=strtolower((string)parse_url($link,PHP_URL_SCHEME));$valid=strlen($link)<=2048&&filter_var($link,FILTER_VALIDATE_URL)!==false&&in_array($scheme,['http','https'],true)&&parse_url($link,PHP_URL_USER)===null&&parse_url($link,PHP_URL_PASS)===null;$context['linkValid']=$valid;if(!$valid)linkedInPostValidationFailure('LINKEDIN_POST_INVALID_URL','LinkedIn-Beitrag konnte nicht veröffentlicht werden: Der Link ist keine gültige absolute HTTP(S)-URL.',$context);return $link;}
function linkedInUnicodeLength(string $value):int{$count=preg_match_all('/./us',$value,$matches);return $count===false?strlen($value):$count;}
function linkedInArticleMetadata(array $data,?string $link,array $context):array{if($link===null)return[null,null];$rawTitle=$data['linkTitle']??null;if(!is_string($rawTitle)||trim($rawTitle)==='')linkedInPostValidationFailure('LINKEDIN_POST_LINK_TITLE_REQUIRED','LinkedIn-Beitrag konnte nicht veröffentlicht werden: Für LinkedIn-Linkposts ist ein Link-Titel erforderlich.',$context);$title=trim($rawTitle);if(linkedInUnicodeLength($title)>=400)linkedInPostValidationFailure('LINKEDIN_POST_LINK_TITLE_TOO_LONG','LinkedIn-Beitrag konnte nicht veröffentlicht werden: Der Link-Titel ist zu lang.',$context);$rawDescription=$data['linkDescription']??'';if(!is_string($rawDescription))linkedInPostValidationFailure('LINKEDIN_POST_LINK_DESCRIPTION_INVALID','LinkedIn-Beitrag konnte nicht veröffentlicht werden: Die Link-Beschreibung ist ungültig.',$context);$description=trim($rawDescription);if(linkedInUnicodeLength($description)>=4086)linkedInPostValidationFailure('LINKEDIN_POST_LINK_DESCRIPTION_TOO_LONG','LinkedIn-Beitrag konnte nicht veröffentlicht werden: Die Link-Beschreibung ist zu lang.',$context);return[$title,$description===''?null:$description];}
function createStoredLinkedInPost(int $userId,array $channel,string $baseText,string $text,?string $link,?string $linkTitle,?string $linkDescription):array{$pdo=db();$now=date('Y-m-d H:i:s');$pdo->beginTransaction();try{$pdo->prepare("INSERT INTO posts(base_text,resolved_text,link_url,link_title,link_description,created_by,status,created_at,updated_at) VALUES(?,?,?,?,?,?,'publishing',?,?)")->execute([$baseText,$text,$link,$linkTitle,$linkDescription,$userId,$now,$now]);$postId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO post_targets(post_id,provider_id,social_account_id,channel_id,final_text,final_link_url,link_title,link_description,status,created_at,updated_at) VALUES(?,'linkedin',?,?,?,?,?,?,'publishing',?,?)")->execute([$postId,$channel['social_account_id'],$channel['id'],$text,$link,$linkTitle,$linkDescription,$now,$now]);$targetId=(int)$pdo->lastInsertId();$pdo->commit();return[$postId,$targetId];}catch(Throwable $exception){if($pdo->inTransaction())$pdo->rollBack();throw $exception;}}
function finishStoredLinkedInPost(int $postId,int $targetId,string $status,?string $externalPostId,?string $errorCode,?string $errorMessage):string{$pdo=db();$now=date('Y-m-d H:i:s');$pdo->beginTransaction();try{$published=$status==='published'?$now:null;$pdo->prepare('UPDATE posts SET status=?,updated_at=? WHERE id=?')->execute([$status,$now,$postId]);$pdo->prepare('UPDATE post_targets SET status=?,external_post_id=?,published_at=?,error_code=?,error_message=?,updated_at=? WHERE id=?')->execute([$status,$externalPostId,$published,$errorCode,$errorMessage,$now,$targetId]);$pdo->commit();return $now;}catch(Throwable $exception){if($pdo->inTransaction())$pdo->rollBack();throw $exception;}}
function recordLinkedInPublishingAttempt(int $postId,int $channelId,string $text,string $visibility,string $status,?string $externalPostId,?string $errorCode):void{db()->prepare("INSERT INTO publishing_attempts(post_id,provider_id,social_channel_id,mode,final_text,visibility,external_post_id,status,error_code,created_at) VALUES(?,'linkedin',?,'live',?,?,?,?,?,?)")->execute([$postId,$channelId,$text,$visibility,$externalPostId,$status,$errorCode,date('Y-m-d H:i:s')]);}
function linkedInPostPayload(string $author,string $text,string $visibility,?string $link,?string $linkTitle,?string $linkDescription):array{$payload=['author'=>$author,'commentary'=>$text,'visibility'=>$visibility,'distribution'=>['feedDistribution'=>'MAIN_FEED','targetEntities'=>[],'thirdPartyDistributionChannels'=>[]],'lifecycleState'=>'PUBLISHED','isReshareDisabledByAuthor'=>false];if($link!==null){$article=['source'=>$link,'title'=>$linkTitle];if($linkDescription!==null)$article['description']=$linkDescription;$payload['content']=['article'=>$article];}return $payload;}
function safeLinkedInPostUpstreamMessage(mixed $value):?string{$message=safeLinkedInLogValue($value);return $message===null?null:preg_replace('#https?://\S+#i','[url]',$message);}
function linkedInPostRequest(string $accessToken,array $payload):string{$headers=['Accept: application/json','Content-Type: application/json','Authorization: Bearer '.$accessToken,'X-Restli-Protocol-Version: 2.0.0','Linkedin-Version: '.LINKEDIN_API_VERSION];$body=@file_get_contents(rtrim(linkedInEndpoint('api'),'/').'/rest/posts',false,stream_context_create(['http'=>['method'=>'POST','timeout'=>10,'ignore_errors'=>true,'header'=>implode("\r\n",$headers),'content'=>json_encode($payload,JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]]));$responseHeaders=$http_response_header??[];$status=0;if(isset($responseHeaders[0])&&preg_match('#\s(\d{3})\s#',$responseHeaders[0],$match))$status=(int)$match[1];$postId=null;foreach($responseHeaders as $header)if(stripos($header,'x-restli-id:')===0){$postId=trim(substr($header,strlen('x-restli-id:')));break;}if($status===201&&is_string($postId)&&$postId!==''&&strlen($postId)<=500)return $postId;$decoded=is_string($body)?json_decode($body,true):null;$upstreamCode=is_array($decoded)&&isset($decoded['code'])&&(is_string($decoded['code'])||is_int($decoded['code']))?(string)$decoded['code']:null;$upstreamMessage=is_array($decoded)?safeLinkedInPostUpstreamMessage($decoded['message']??null):null;error_log('SocialPost LinkedIn post '.json_encode(['phase'=>'linkedin_post_upstream','httpStatus'=>$status?:null,'linkedinErrorCode'=>$upstreamCode,'linkedinErrorMessage'=>$upstreamMessage,'responseIsJson'=>is_array($decoded)],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE));if($status===401)throw new OAuthException('LINKEDIN_POST_TOKEN','Die LinkedIn-Verbindung ist abgelaufen. Bitte erneut verbinden.',422);if($status===403)throw new OAuthException('LINKEDIN_POST_FORBIDDEN','LinkedIn erlaubt die Veröffentlichung für dieses Profil nicht.',422);if($status===429)throw new OAuthException('LINKEDIN_POST_RATE_LIMIT','LinkedIn erlaubt derzeit keine weitere Veröffentlichung. Bitte später erneut versuchen.',429);if($status===400||$status===422)throw new OAuthException('LINKEDIN_POST_UPSTREAM_VALIDATION','LinkedIn hat den bereits lokal validierten Beitrag abgelehnt. Details wurden sicher im Serverlog erfasst.',422);throw new OAuthException('LINKEDIN_POST_FAILED','LinkedIn konnte den Beitrag nicht veröffentlichen.',502);}
function listPosts():never{requireAuth();$rows=db()->query("SELECT p.id,p.created_at,p.status,p.base_text,p.resolved_text,p.link_url,p.link_title,p.link_description,t.provider_id,t.final_text,t.final_link_url,t.link_title target_link_title,t.link_description target_link_description,t.status target_status,t.external_post_id,t.published_at,c.display_name channel_name FROM posts p LEFT JOIN post_targets t ON t.post_id=p.id LEFT JOIN social_channels c ON c.id=t.channel_id ORDER BY p.created_at DESC,p.id DESC,t.id")->fetchAll();$posts=array_map(fn(array $row)=>['id'=>(int)$row['id'],'createdAt'=>$row['created_at'],'baseText'=>$row['base_text'],'resolvedText'=>$row['resolved_text'],'linkUrl'=>$row['link_url'],'linkTitle'=>$row['link_title'],'linkDescription'=>$row['link_description'],'status'=>$row['target_status']??$row['status'],'providerId'=>$row['provider_id'],'channelName'=>$row['channel_name'],'finalText'=>$row['final_text'],'finalLinkUrl'=>$row['final_link_url'],'finalLinkTitle'=>$row['target_link_title'],'finalLinkDescription'=>$row['target_link_description'],'externalPostId'=>$row['external_post_id'],'publishedAt'=>$row['published_at']],$rows);ok(['posts'=>$posts]);}
function publishLinkedInTestPost():never{
    $user=requireAdmin();requireCsrf();$data=input();$channelId=$data['channelId']??null;$confirmed=($data['confirmed']??null)===true;$rawText=$data['text']??null;$context=['hasText'=>is_string($rawText)&&trim($rawText)!=='','hasLink'=>false,'linkValid'=>false,'channelPresent'=>false,'channelPublishable'=>false,'scopePresent'=>false,'confirmed'=>$confirmed];
    if(!is_int($channelId)||$channelId<1)linkedInPostValidationFailure('LINKEDIN_POST_CHANNEL_REQUIRED','LinkedIn-Beitrag konnte nicht veröffentlicht werden: Es wurde kein veröffentlichungsfähiger LinkedIn-Kanal ausgewählt.',$context);
    if(!$confirmed)linkedInPostValidationFailure('LINKEDIN_POST_CONFIRMATION_REQUIRED','LinkedIn-Beitrag konnte nicht veröffentlicht werden: Die zweite Veröffentlichungsbestätigung fehlt.',$context);
    $baseText=$data['baseText']??null;if(!is_string($baseText)||strlen($baseText)>50000)linkedInPostValidationFailure('LINKEDIN_POST_BASE_TEXT_INVALID','LinkedIn-Beitrag konnte nicht veröffentlicht werden: Der Basistext ist ungültig.',$context);
    if(!is_string($rawText)||trim($rawText)===''||strlen(trim($rawText))>3000)linkedInPostValidationFailure('LINKEDIN_POST_TEXT_REQUIRED','LinkedIn-Beitrag konnte nicht veröffentlicht werden: Der Beitragstext fehlt oder ist zu lang.',$context);$text=trim($rawText);
    $link=linkedInPostLink($data,$context);[$linkTitle,$linkDescription]=linkedInArticleMetadata($data,$link,$context);$visibility=$data['visibility']??null;if(!is_string($visibility)||!in_array($visibility,['PUBLIC','CONNECTIONS'],true))linkedInPostValidationFailure('LINKEDIN_POST_VISIBILITY_INVALID','LinkedIn-Beitrag konnte nicht veröffentlicht werden: Die Sichtbarkeit ist ungültig.',$context);
    $stmt=db()->prepare("SELECT c.id,c.social_account_id,c.external_channel_id,c.channel_type,c.status,c.can_publish,a.external_account_id,a.access_token_encrypted,a.token_expires_at,a.scopes,a.status account_status FROM social_channels c JOIN social_accounts a ON a.id=c.social_account_id WHERE c.id=? AND c.provider_id='linkedin'");$stmt->execute([$channelId]);$channel=$stmt->fetch();$context['channelPresent']=(bool)$channel;
    if(!$channel)linkedInPostValidationFailure('LINKEDIN_POST_CHANNEL_REQUIRED','LinkedIn-Beitrag konnte nicht veröffentlicht werden: Es wurde kein veröffentlichungsfähiger LinkedIn-Kanal ausgewählt.',$context,404);
    $context['scopePresent']=in_array('w_member_social',linkedInScopeList($channel['scopes']),true);if(!$context['scopePresent'])linkedInPostValidationFailure('LINKEDIN_POST_SCOPE_REQUIRED','LinkedIn-Beitrag konnte nicht veröffentlicht werden: Die erforderliche Berechtigung w_member_social fehlt.',$context);
    $context['channelPublishable']=$channel['channel_type']==='personal'&&$channel['status']==='active'&&$channel['account_status']==='connected'&&(int)$channel['can_publish']===1&&(int)$channel['social_account_id']>0&&is_string($channel['external_channel_id'])&&trim($channel['external_channel_id'])!==''&&is_string($channel['external_account_id'])&&trim($channel['external_account_id'])!=='';
    if(!$context['channelPublishable'])linkedInPostValidationFailure('LINKEDIN_POST_CHANNEL_NOT_PUBLISHABLE','LinkedIn-Beitrag konnte nicht veröffentlicht werden: Es wurde kein veröffentlichungsfähiger persönlicher LinkedIn-Kanal ausgewählt.',$context);
    if(is_string($channel['token_expires_at'])&&strtotime($channel['token_expires_at'])<=time())linkedInPostValidationFailure('LINKEDIN_POST_TOKEN','LinkedIn-Beitrag konnte nicht veröffentlicht werden: Die LinkedIn-Verbindung ist abgelaufen.',$context);
    linkedInPostValidationLog('LINKEDIN_POST_VALIDATION_PASSED',$context);[$postId,$targetId]=createStoredLinkedInPost((int)$user['id'],$channel,$baseText,$text,$link,$linkTitle,$linkDescription);
    try{$accessToken=decryptSecret((string)$channel['access_token_encrypted']);$payload=linkedInPostPayload('urn:li:person:'.$channel['external_account_id'],$text,$visibility,$link,$linkTitle,$linkDescription);$externalPostId=linkedInPostRequest($accessToken,$payload);$publishedAt=finishStoredLinkedInPost($postId,$targetId,'published',$externalPostId,null,null);recordLinkedInPublishingAttempt($postId,$channelId,$text,$visibility,'success',$externalPostId,null);ok(['status'=>'success','message'=>'LinkedIn-Beitrag erfolgreich veröffentlicht.','postId'=>$externalPostId,'storedPostId'=>$postId,'publishedAt'=>date(DATE_ATOM,strtotime($publishedAt)),'channelId'=>$channelId]);}catch(OAuthException $exception){finishStoredLinkedInPost($postId,$targetId,'failed',null,$exception->errorCode,$exception->getMessage());recordLinkedInPublishingAttempt($postId,$channelId,$text,$visibility,'failed',null,$exception->errorCode);throw $exception;}catch(CryptoException){$code='LINKEDIN_POST_TOKEN';$message='Die LinkedIn-Verbindung ist ungültig. Bitte erneut verbinden.';finishStoredLinkedInPost($postId,$targetId,'failed',null,$code,$message);recordLinkedInPublishingAttempt($postId,$channelId,$text,$visibility,'failed',null,$code);throw new OAuthException($code,$message,422);}
}
