<?php
declare(strict_types=1);

const MEDIA_STORAGE_DIR='/var/lib/socialdeck/media';
const MEDIA_LIMITS=['image'=>52428800,'video'=>524288000,'document'=>104857600];
const MEDIA_MIMES=['image'=>['image/jpeg'=>'jpg','image/png'=>'png','image/gif'=>'gif'],'video'=>['video/mp4'=>'mp4'],'document'=>['application/pdf'=>'pdf','application/msword'=>'doc','application/vnd.openxmlformats-officedocument.wordprocessingml.document'=>'docx','application/vnd.ms-powerpoint'=>'ppt','application/vnd.openxmlformats-officedocument.presentationml.presentation'=>'pptx']];

function mediaLog(string $phase,array $values=[]):void{error_log('SocialPost LinkedIn media '.json_encode(['phase'=>$phase,'media_type'=>$values['media_type']??null,'file_size'=>$values['file_size']??null,'httpStatus'=>$values['httpStatus']??null,'linkedinErrorCode'=>$values['linkedinErrorCode']??null,'processingStatus'=>$values['processingStatus']??null,'externalMediaUrn'=>$values['externalMediaUrn']??null],JSON_UNESCAPED_SLASHES));}
function mediaFailure(string $code,string $message,int $status=422):never{throw new OAuthException($code,$message,$status);}
function validateIncomingMedia(array $file):array{
    if(($file['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)return[];
    if(($file['error']??UPLOAD_ERR_OK)!==UPLOAD_ERR_OK||!is_uploaded_file((string)($file['tmp_name']??'')))mediaFailure('MEDIA_LOCAL_UPLOAD_FAILED','Die Mediendatei konnte nicht sicher empfangen werden.');
    $size=(int)($file['size']??0);if($size<1)mediaFailure('MEDIA_EMPTY','Die Mediendatei ist leer.');
    $mime=(new finfo(FILEINFO_MIME_TYPE))->file((string)$file['tmp_name']);$type=null;$extension=null;foreach(MEDIA_MIMES as $candidate=>$mimes)if(isset($mimes[$mime])){$type=$candidate;$extension=$mimes[$mime];break;}
    if($type===null)mediaFailure('MEDIA_TYPE_INVALID','Dieser Dateityp wird für LinkedIn nicht unterstützt.');if($size>MEDIA_LIMITS[$type])mediaFailure('MEDIA_TOO_LARGE','Die Mediendatei überschreitet das zulässige Größenlimit.');
    if($type==='image'){$dimensions=@getimagesize((string)$file['tmp_name']);if(!is_array($dimensions)||($dimensions[0]*$dimensions[1])>=36152320)mediaFailure('MEDIA_IMAGE_DIMENSIONS_INVALID','Das Bild ist ungültig oder überschreitet die LinkedIn-Pixelgrenze.');}
    $name=trim(basename(str_replace('\\','/',(string)($file['name']??'medium'))));$name=preg_replace('/[^\pL\pN._ -]+/u','_',$name)?:'medium.'.$extension;$name=mb_substr($name,0,255);
    return['tmp_name'=>(string)$file['tmp_name'],'media_type'=>$type,'mime_type'=>$mime,'extension'=>$extension,'file_size'=>$size,'original_filename'=>$name];
}
function storeIncomingMedia(array $media,array $channel):array{
    if(!is_dir(MEDIA_STORAGE_DIR)&&!mkdir(MEDIA_STORAGE_DIR,0700,true)&&!is_dir(MEDIA_STORAGE_DIR))mediaFailure('MEDIA_STORAGE_FAILED','Der lokale Medienspeicher ist nicht verfügbar.',500);
    $key=bin2hex(random_bytes(24)).'.'.$media['extension'];$path=MEDIA_STORAGE_DIR.'/'.$key;if(!move_uploaded_file($media['tmp_name'],$path)){mediaFailure('MEDIA_STORAGE_FAILED','Die Mediendatei konnte nicht gespeichert werden.',500);}chmod($path,0600);$now=date('Y-m-d H:i:s');
    try{db()->prepare("INSERT INTO media_assets(provider_id,social_account_id,channel_id,media_type,original_filename,mime_type,file_size,storage_key,upload_status,processing_status,created_at,updated_at) VALUES('linkedin',?,?,?,?,?,?,?,'stored','pending',?,?)")->execute([$channel['social_account_id'],$channel['id'],$media['media_type'],$media['original_filename'],$media['mime_type'],$media['file_size'],$key,$now,$now]);}catch(Throwable $e){@unlink($path);throw $e;}
    return $media+['id'=>(int)db()->lastInsertId(),'storage_key'=>$key,'path'=>$path];
}
function linkedInMediaJson(string $method,string $url,string $token,?array $payload=null):array{
    $headers=['Authorization: Bearer '.$token,'Linkedin-Version: '.LINKEDIN_API_VERSION,'X-Restli-Protocol-Version: 2.0.0','Accept: application/json'];if($payload!==null)$headers[]='Content-Type: application/json';$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>$headers,CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>false,CURLOPT_TIMEOUT=>30]);if($payload!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($payload,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES));$body=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$error=curl_error($ch);curl_close($ch);$decoded=is_string($body)?json_decode($body,true):null;if($error!=='')mediaFailure('MEDIA_TRANSPORT_FAILED','Die Verbindung zum LinkedIn-Mediendienst ist fehlgeschlagen.',502);if($status<200||$status>=300){$code=is_array($decoded)?($decoded['code']??$decoded['error']??null):null;mediaLog('media_api',['httpStatus'=>$status,'linkedinErrorCode'=>is_scalar($code)?(string)$code:null]);if($status===401)mediaFailure('MEDIA_LINKEDIN_TOKEN','Die LinkedIn-Verbindung ist abgelaufen.');if($status===403)mediaFailure('MEDIA_LINKEDIN_FORBIDDEN','LinkedIn erlaubt diesen Medienupload nicht.');if($status===429)mediaFailure('MEDIA_LINKEDIN_RATE_LIMIT','LinkedIn erlaubt derzeit keinen weiteren Medienupload.',429);mediaFailure($status>=500?'MEDIA_LINKEDIN_UPSTREAM':'MEDIA_LINKEDIN_VALIDATION','LinkedIn hat den Medienupload abgelehnt.',502);}if(!is_array($decoded))mediaFailure('MEDIA_LINKEDIN_RESPONSE','LinkedIn hat eine ungültige Medienantwort geliefert.',502);return$decoded;
}
function uploadMediaPart(string $url,string $path,int $first,int $last,string $mime):string{
    $handle=fopen($path,'rb');if(!$handle)mediaFailure('MEDIA_STORAGE_FAILED','Die lokale Mediendatei ist nicht lesbar.',500);fseek($handle,$first);$remaining=$last-$first+1;$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_UPLOAD=>true,CURLOPT_INFILESIZE=>$remaining,CURLOPT_HTTPHEADER=>['Content-Type: '.$mime],CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_TIMEOUT=>300,CURLOPT_READFUNCTION=>function($curl,$fd,$length)use($handle,&$remaining){if($remaining<=0)return'';$data=fread($handle,min($length,$remaining));$remaining-=strlen($data);return$data;}]);$response=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$headerSize=(int)curl_getinfo($ch,CURLINFO_HEADER_SIZE);$error=curl_error($ch);curl_close($ch);fclose($handle);if($error!==''||$status<200||$status>=300)mediaFailure('MEDIA_UPLOAD_FAILED','Die Mediendatei konnte nicht zu LinkedIn übertragen werden.',502);$headers=substr((string)$response,0,$headerSize);return preg_match('/^ETag:\s*(.+)$/mi',$headers,$match)?trim($match[1]," \t\r\n\""):'';
}
function uploadLinkedInMedia(array $asset,string $owner,string $token):string{
    $type=$asset['media_type'];$plural=['image'=>'images','video'=>'videos','document'=>'documents'][$type];$request=['owner'=>$owner];if($type==='video')$request['fileSizeBytes']=$asset['file_size'];$init=linkedInMediaJson('POST',rtrim(linkedInEndpoint('api'),'/').'/rest/'.$plural.'?action=initializeUpload',$token,['initializeUploadRequest'=>$request]);$value=$init['value']??[];$urn=$value[$type]??null;if(!is_string($urn)||!str_starts_with($urn,'urn:li:'.$type.':'))mediaFailure('MEDIA_INITIALIZE_FAILED','LinkedIn hat keine gültige Medien-ID geliefert.',502);db()->prepare("UPDATE media_assets SET external_media_id=?,upload_status='uploading',updated_at=? WHERE id=?")->execute([$urn,date('Y-m-d H:i:s'),$asset['id']]);
    $etags=[];if($type==='video'){foreach($value['uploadInstructions']??[] as $instruction){$url=$instruction['uploadUrl']??null;$first=$instruction['firstByte']??null;$last=$instruction['lastByte']??null;if(!is_string($url)||!is_int($first)||!is_int($last))mediaFailure('MEDIA_INITIALIZE_FAILED','LinkedIn hat ungültige Uploadanweisungen geliefert.',502);$etags[]=uploadMediaPart($url,$asset['path'],$first,$last,$asset['mime_type']);}linkedInMediaJson('POST',rtrim(linkedInEndpoint('api'),'/').'/rest/videos?action=finalizeUpload',$token,['finalizeUploadRequest'=>['video'=>$urn,'uploadToken'=>(string)($value['uploadToken']??''),'uploadedPartIds'=>$etags]]);}else{$url=$value['uploadUrl']??null;if(!is_string($url))mediaFailure('MEDIA_INITIALIZE_FAILED','LinkedIn hat keine Uploadadresse geliefert.',502);uploadMediaPart($url,$asset['path'],0,$asset['file_size']-1,$asset['mime_type']);}
    db()->prepare("UPDATE media_assets SET upload_status='uploaded',processing_status='processing',updated_at=? WHERE id=?")->execute([date('Y-m-d H:i:s'),$asset['id']]);mediaLog('uploaded',['media_type'=>$type,'file_size'=>$asset['file_size'],'externalMediaUrn'=>$urn]);return$urn;
}
function finishMediaAsset(int $id,int $postId,bool $success,?string $code=null,?string $message=null):void{db()->prepare('UPDATE media_assets SET post_id=?,processing_status=?,error_code=?,error_message=?,updated_at=? WHERE id=?')->execute([$postId,$success?'available':'failed',$code,$message,date('Y-m-d H:i:s'),$id]);}
